### ISSUE TITLE
interesting paper

### ISSUE THREAD

**Issue by parsifal9** [tycui/GWAS_NN#1]
Hi Tianyu,
I am very interested in this package and in your paper. It tackles a number of things (variable interactions, importance measures, null distributions and significance levels) not usual in deep learning methods. 

My "issue" is more of a question
1) the code does not the the GPU, is this because you did not expect a speedup from using it?
2) the examples are quite small (65 genes). Can it handle larger (more genes) data sets or do you have plans in this direction?
3) the method summarized SNPs to genes but  could it be "cut down" and simply look for interactions between  
variables (ie gene transcriptome levels or indeed any other set of variables).

Thanks
Bye

**Comment by tycui** [comment]
Hi parsifal9,
Thanks for your interest in our work and bring up those "issues":

1. GPU didn't really improve much in our case, because the architecture was rather simple and shallow, and the size of the dataset is huge, so transferring the data from CPU to GPU can take a long time. Moreover, we also need to train the main effect NNs multiple times to estimate the null distribution, and CPU is easier for parallel computing in our devices.
2. Indeed the size of genes is small in this paper, even though, training the model is already time-consuming. We are planning to run a whole genome-wide interaction detection with distributed neural networks.
3. That's a good "issue" too. The motivation is that the gene transcriptome level or gene expression data is very small in our case, so we cannot train NNs well on that. But comparing the real gene expression with the summarized SNPs is interesting to us.

Cheers,
Tianyu
