### ISSUE TITLE
nan

### ISSUE THREAD

**Issue by snowformatics** [tycui/GWAS_NN#2]
Hi,
thanks for sharing the code and your paper, very interesting!

I am getting "nan" reports after running my samples (200 samples with one phenotype+ 14000000 SNPs):

nan
BNN slope is nan
BNN intercept is nan
EPOACH 1: TRAIN LOSS: nan; KL REG: nan; TEST LOSS IS: nan.
EPOACH 101: TRAIN LOSS: nan; KL REG: nan; TEST LOSS IS: nan.
BNN model :
Explained variance of 65 genes is: nan.

What does that mean? No interaction found? 
Thanks a lot
Stefanie

**Comment by tycui** [comment]
Hi Stefanie,

Thanks for your interest in using the method. 'nan' means that your NNs learn nothing. Your data format may not be consistent with the code, since the method gives nan even before the training (from the output file). So I suggest that you could check the data format first. Another suggestion is that you could increase the batch_size, for example, int(x_train.shape[0] / 5), because you only have 200 samples in total.

Moreover, NN is a joint model of all SNPs/genes, so I think 200 samples are not sufficient to learn anything useful. You could either increase the sample size or decrease the number of SNPs. In our case, we used ~400,000 samples for 65 genes.

Let me know if you have any questions.

Cheers,
Tianyu

**Comment by snowformatics** [comment]
Thanks a lot, Tianyu! It looks like the sample size is too small, all the rest looks fine.

Thanks again for your efforts :)
